-- schemagraph probe 검증 fixture (H2).
-- sqlite/mysql fixture와 같은 모양을 H2 방언으로 — 순환 FK, view, 루틴이
-- 들어가야 프로브가 카탈로그+몸체를 모두 수확하는지 검증된다.

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(200)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    total DECIMAL(10,2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    sku VARCHAR(50) NOT NULL,
    qty INT NOT NULL,
    CONSTRAINT fk_items_order FOREIGN KEY (order_id) REFERENCES orders(id)
);

-- 순환 FK — 선언 시점 검사를 피하려고 테이블을 다 만든 뒤 제약을 붙인다.
CREATE TABLE loop_a (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    b_id BIGINT
);
CREATE TABLE loop_b (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    a_id BIGINT
);
ALTER TABLE loop_a ADD CONSTRAINT fk_a_b FOREIGN KEY (b_id) REFERENCES loop_b(id);
ALTER TABLE loop_b ADD CONSTRAINT fk_b_a FOREIGN KEY (a_id) REFERENCES loop_a(id);

CREATE TABLE loop_self (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    CONSTRAINT fk_self FOREIGN KEY (parent_id) REFERENCES loop_self(id)
);

-- 도달 불가 후보 — 아무것도 참조하지 않고 아무에게도 참조되지 않는다.
CREATE TABLE orphaned_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message VARCHAR(200)
);

CREATE INDEX idx_orders_customer ON orders(customer_id);
CREATE UNIQUE INDEX uq_customers_email ON customers(email);

CREATE VIEW order_totals AS
    SELECT c.id AS customer_id, c.name, SUM(o.total) AS total
    FROM customers c JOIN orders o ON o.customer_id = c.id
    GROUP BY c.id, c.name;
